### ISSUE TITLE
LAPJV算法的原理是什么？

### ISSUE THREAD

**Issue by HXMing** [thu-vis/fast-lapjv#1]
LAPJV的原理是什么啊，在网上只找到了一篇87年的论文，不太看得懂，有简单易懂一点的学习资料吗。还有就是LAPJV算法可以用来求最大值吗？尝试着吧输入的矩阵取相反数来求解发现没用，因为直接死机了。

**Comment by chencjGene** [comment]
你好！在我们实现过程中，发现最好的参考材料还是87年的论文：A shortest augmenting path algorithm for dense and sparse linear assignment problems。代码中也有一些注释帮助理解。
因为LAPJV无法处理负数，你可以取相反数后，给所有数加上一个常数，使得所有数非负。

**Comment by HXMing** [comment]
好的，谢谢。
